/* eslint-disable */
require('./calendar')
require('./cross')
require('./cw')
require('./document')
require('./envelope')
require('./library')
require('./money')
require('./moon')
require('./plain')
require('./print')
require('./question')
require('./questions')
require('./student')
require('./sun')
require('./univer')
